### ISSUE TITLE
Resolve Dependency Conflict Error

### ISSUE THREAD

**Issue by norvinteo** [datadirr/qr_bar_code#2]
I got this error

Error: Failed running flutter pub get...
Because qr_bar_code >=1.2.0 depends on plugin_platform_interface ^2.1.5 and custom_widget depends on plugin_platform_interface 2.1.3, qr_bar_code >=1.2.0 is forbidden.
So, because custom_widget depends on qr_bar_code ^1.2.0, version solving failed.

How can I fix it?

**Comment by datadirr** [comment]
Hi,

Please upgrade your all packages.
